CREATE DATABASE STUDENT_MANAGEMENT;
USE STUDENT_MANAGEMENT;

CREATE TABLE STUDENTS(
STUDENT_ID INT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT,
COURSE VARCHAR(50),
MARKS INT,
CITY VARCHAR(50)
);

INSERT INTO STUDENTS
(STUDENT_ID,NAME,AGE,COURSE,MARKS,CITY)
VALUES
(1010,"YASH",19,"DATA SCIENCE",80,"PUNE"),
(1011,"RAHUL",20,"DATA SCIENCE",85,"MUMBAI"),
(1012,"ROHIT",21,"IT",73,"NASHIK"),
(1013,"BOB",22,"IT",91,"NAGPUR"),
(1014,"DAVID",23,"ECS",92,"NAGPUR"),
(1015,"SAM",22,"BCA",65,"MUMBAI");

SELECT * FROM STUDENTS;
SELECT NAME
FROM STUDENTS
WHERE MARKS > 80;

SELECT NAME 
FROM STUDENTS
WHERE CITY="MUMBAI";

SELECT max(MARKS)
FROM STUDENTS;

SELECT min(MARKS)
FROM STUDENTS;

SELECT avg(MARKS)
FROM STUDENTS;

SELECT COUNT(NAME)
FROM STUDENTS;

SELECT MARKS 
FROM STUDENTS
ORDER BY MARKS DESC;

SELECT COURSE,COUNT(*)
FROM STUDENTS
GROUP BY COURSE;

SELECT NAME
FROM STUDENTS
WHERE AGE > 20;

SELECT NAME,MARKS
FROM STUDENTS
WHERE MARKS=92;